#!/usr/bin/env bash

#fix nginx listening on port 80

cd /etc/nginx/sites-enabled/ || exit;
#go to the sites-enabled folder

rm default;
#remove the default file

ln -s /etc/nginx/sites-available/default default;
#create a symbolic link

service nginx restart;
#restart nginx server


