#!/usr/bin/env bash
#using the case instead od if
while ((i <= 20))
do
	case $i in

		4)
			echo "$i"
			echo "bad luck from china"
			;;
		9)
			echo "$i"
			echo "bad luck from japan"
			;;
		17)
			echo "$i"
			echo "bad luck from italy"
			;;
		*)
			echo "$i"
			;;
		esac
	((i++))
done
